import {
  FiAlertCircle,
  FiArrowDownCircle,
  FiArrowLeftCircle,
  FiArrowRightCircle,
  FiDollarSign,
  FiCheck,
  FiCheckCircle,
  FiCheckSquare,
  FiChevronRight,
  FiChevronLeft,
  FiClock,
  FiCreditCard,
  FiEdit2,
  FiFile,
  FiHelpCircle,
  FiImage,
  FiMail,
  FiMoreHorizontal,
  FiLock,
  FiPlus,
  FiPlusCircle,
  FiRefreshCcw,
  FiSave,
  FiSearch,
  FiSettings,
  FiShare2,
  FiStar,
  FiTrash,
  FiTrendingDown,
  FiTrendingUp,
  FiUser,
  FiXCircle,
  FiXSquare,
  FiX,
} from 'react-icons/fi';

import {
  FaStar,
  FaUser,
  FaWhatsapp,
  FaImages,
  FaShareAlt,
  FaRegChartBar,
  FaRss,
  FaUsers,
} from 'react-icons/fa';

interface IconsMap {
  [key: string]: JSX.Element;
}
export const Icons: IconsMap = {
  'alert-circle': <FiAlertCircle />,
  'arrow-down-circle': <FiArrowDownCircle />,
  'arrow-left-circle': <FiArrowLeftCircle />,
  'arrow-right-circle': <FiArrowRightCircle />,
  'dollar-sign': <FiDollarSign />,
  check: <FiCheck />,
  'check-circle': <FiCheckCircle />,
  'check-square': <FiCheckSquare />,
  'chevron-right': <FiChevronRight />,
  'chevron-left': <FiChevronLeft />,
  clock: <FiClock />,
  'credit-card': <FiCreditCard />,
  'edit-2': <FiEdit2 />,
  file: <FiFile />,
  'help-circle': <FiHelpCircle />,
  image: <FiImage />,
  images: <FaImages />,
  mail: <FiMail />,
  'more-horizontal': <FiMoreHorizontal />,
  lock: <FiLock />,
  plus: <FiPlus />,
  'plus-circle': <FiPlusCircle />,
  'refresh-ccw': <FiRefreshCcw />,
  'reg-chart-bar': <FaRegChartBar />,
  rss: <FaRss />,
  save: <FiSave />,
  search: <FiSearch />,
  settings: <FiSettings />,
  'share-alt': <FaShareAlt />,
  'share-2': <FiShare2 />,
  star: <FiStar />,
  'star-fa': <FaStar />,
  trash: <FiTrash />,
  'trending-down': <FiTrendingDown />,
  'treding-up': <FiTrendingUp />,
  user: <FiUser />,
  'user-fa': <FaUser />,
  users: <FaUsers />,
  'x-circle': <FiXCircle />,
  square: <FiXSquare />,
  whatsapp: <FaWhatsapp />,
  x: <FiX />,
};
