import {
  FiAlertCircle,
  FiArrowDownCircle,
  FiArrowLeftCircle,
  FiArrowRightCircle,
  FiDollarSign,
  FiCheckSquare,
  FiClock,
  FiCreditCard,
  FiEdit2,
  FiFile,
  FiHelpCircle,
  FiImage,
  FiMail,
  FiMoreHorizontal,
  FiLock,
  FiPlus,
  FiPlusCircle,
  FiRefreshCcw,
  FiSave,
  FiSearch,
  FiSettings,
  FiShare2,
  FiStar,
  FiTrash,
  FiTrendingDown,
  FiUser,
  FiXCircle,
  FiXSquare,
} from 'react-icons/fi';

import {
  FaStar,
  FaUser,
  FaWhatsapp,
  FaImages,
  FaShareAlt,
  FaRss,
  FaUsers,
  FaTimes,
  FaChevronRight,
  FaChevronLeft,
  FaCheck,
  FaCheckCircle,
  FaChartBar,
  FaChartLine,
  FaPencilAlt,
  FaEnvelope,
  FaComment,
  FaEllipsisH,
  FaFileExcel,
  FaQuestion,
  FaChartPie,
} from 'react-icons/fa';

interface IconsMap {
  [key: string]: JSX.Element;
}
export const Icons: IconsMap = {
  'alert-circle': <FiAlertCircle />,
  'arrow-down-circle': <FiArrowDownCircle />,
  'arrow-left-circle': <FiArrowLeftCircle />,
  'arrow-right-circle': <FiArrowRightCircle />,
  'dollar-sign': <FiDollarSign />,
  check: <FaCheck />,
  'chart-line': <FaChartLine />,
  'chart-pie': <FaChartPie />,
  'check-circle': <FaCheckCircle />,
  'check-square': <FiCheckSquare />,
  'chevron-right': <FaChevronRight />,
  'chevron-left': <FaChevronLeft />,
  clock: <FiClock />,
  'credit-card': <FiCreditCard />,
  comment: <FaComment />,
  edit: <FaPencilAlt />,
  'three-circles': <FaEllipsisH />,
  file: <FiFile />,
  'file-excel': <FaFileExcel />,
  help: <FaQuestion />,
  'help-circle': <FiHelpCircle />,
  image: <FiImage />,
  images: <FaImages />,
  mail: <FaEnvelope />,
  'more-horizontal': <FiMoreHorizontal />,
  lock: <FiLock />,
  plus: <FiPlus />,
  'plus-circle': <FiPlusCircle />,
  'refresh-ccw': <FiRefreshCcw />,
  'reg-chart-bar': <FaChartBar />,
  rss: <FaRss />,
  save: <FiSave />,
  search: <FiSearch />,
  settings: <FiSettings />,
  'share-alt': <FaShareAlt />,
  'share-2': <FiShare2 />,
  star: <FiStar />,
  'star-fa': <FaStar />,
  trash: <FiTrash />,
  'trending-down': <FiTrendingDown />,
  'treding-up': <FaChartLine />,
  user: <FiUser />,
  'user-fa': <FaUser />,
  users: <FaUsers />,
  'x-circle': <FiXCircle />,
  square: <FiXSquare />,
  whatsapp: <FaWhatsapp />,
  x: <FaTimes />,
};
