export const ROUTES = {
  GECO: '/',
  HOME: '/home',
  LOGIN: '/login',
  RESET_PASSWORD: '/recovery/reset-password',
  RESET_PASSWORD_SUCCESS: '/recovery/reset-success',
  CONTACTS: {
    ADD_CONTACT: '/contacts/success-add-contact',
    CONTACS_LIST: '/contacts/list',
    OPTIONS: '/contacts/options',
  },
  GROUPS: {
    ROOT: '/contacts/groups',
    ADD_GROUP_INFO: '/add-group/info',
    ADD_GROUP_MEMBERS: '/add-group/members',
    ADD_GROUP_SUCCESS: '/sucess-add-group',
    GROUP_SEE_MORE: '/:id',
    EDIT_GROUP_SELECT: '/edit-group',
    EDIT_GROUP_STEP1: '/edit-group/:id',
    EDIT_GROUP_STEP2: '/edit-group/:id/members',
    EDIT_GROUP_STEP3: '/edit-group/:id/add-members',
  },
  USER: {
    EDIT_SUCCESS: '/user/edit-success',
  },
  AD: {
    ROOT: '/ad',
    CREATE: {
      ROOT: '/create',
      SIZE: '/size',
      IMAGE: '/image',
      CONTENT_BUILDER: '/content-builder',
      AD_GENERATION: '/ad_generation',
      INFORMATION: '/information',
      SUCCESS: '/success',
      // Rutas legacy (mantener por compatibilidad)
      CONTENT: '/content',
      IMAGE_TYPE: '/image-type',
      IMAGE_AI: '/image/ai',
      IMAGE_OWN: '/image/own',
      PATTERN: '/pattern',
      PALLETTE: '/pallette',
    },
    LIST: {
      ROOT: '/list',
      VIEW: '/view',
    },
    EDIT: {
      ROOT: '/edit',
      INFORMATION: '/information',
      SUCCESS: '/success',
    },
    ERROR: '/error',
  },
  STRATEGY: {
    ROOT: '/strategy',
    CREATE: {
      ROOT: '/create',
      INFORMATION: '/information',
      ADS: '/ads',
      GROUPS: '/groups',
      PERIOD: '/period',
      PERIODICITY: '/periodicity',
      FORM: '/form',
      RESUME: '/resume',
      SUCCESS: '/success',
    },
    EDIT: {
      ROOT: '/edit',
      INFORMATION: '/information',
      ADS: '/ads',
      GROUPS: '/groups',
      PERIOD: '/period',
      PERIODICITY: '/periodicity',
      FORM: '/form',
      RESUME: '/resume',
      SUCCESS: '/success',
    },
    LIST: {
      ROOT: '/list',
    },
    ERROR: '/error',
  },
  SIGN_UP: {
    SIGN_UP_SUCCESSFUL: '/sign-up/sign-up-successful',
  },
  RESPONSES: {
    ROOT: '/responses',
    LIST: '/responses/list',
    VIEW: '/responses/view',
  },
};
